### ISSUE TITLE
Will there be a separate (or internal) node location configuration?

### ISSUE THREAD

**Issue by dev10** [offscale/offsetup-rfc#1]
Apache Brooklyn has a YAML location configuration:

Excerpt from https://brooklyn.apache.org/v/latest/locations/
> Locations are the environments to which Brooklyn deploys applications. Most commonly these are cloud services such as AWS, GCE, and IBM Softlayer. Brooklyn also supports deploying to a pre-provisioned network or to localhost (primarily useful for testing blueprints).

This configures where to look for nodes and how to connect via ssh. You can bring your own node (BYON https://brooklyn.apache.org/v/latest/locations/#byon) eg:

```
location:
  byon:
    user: brooklyn
    privateKeyFile: ~/.ssh/brooklyn.pem
    hosts:
    - 192.168.0.18
    - 192.168.0.19
``` 

If we do support it, then:
* What type of configuration/layout will it support for applications on the nodes, homogeneous/ heterogeneous (specifically regarding databases and replication etc). Will each be standalone or will they need to replicate?
* Status report of configuration for nodes and application(s): once off or continuous through web panel?
    * We can add properties like Brooklyn for secure info (web interface).
